AWSTemplateFormatVersion: '2010-09-09'
# *** Change this to something useful for you!
Description: github-codepipeline-app

# This is just here as an example resource

Resources:
  ApplicationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AWS::StackName
Outputs:
  BucketName:
    Value: !Ref ApplicationBucket
    Description: Name of the Application S3 bucket.
  BucketArn:
    Value: !GetAtt ApplicationBucket.Arn
    Description: The Bucket ARN.