AWSTemplateFormatVersion: '2010-09-09'
Description: This stack deploys an S3 Bucket

Parameters:
  S3BucketName:
    Type: String

Resources:
  ApplicationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName

Outputs:
  BucketName:
    Value: !Ref ApplicationBucket
    Description: Name of the AWS S3 bucket.
  BucketArn:
    Value: !GetAtt ApplicationBucket.Arn
    Description: The Bucket ARN.